BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TransferDaemons" (
	"sender_id"	INTEGER NOT NULL,
	"receiver_id"	INTEGER NOT NULL,
	"amount"	REAL NOT NULL,
	"next_transfer_datetime"	TEXT NOT NULL,
	"frequency"	INTEGER NOT NULL,
	FOREIGN KEY("sender_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY("receiver_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("sender_id","receiver_id")
);
CREATE TABLE IF NOT EXISTS "Transfer" (
	"id"	INTEGER NOT NULL,
	"sender_id"	INTEGER NOT NULL,
	"receiver_id"	INTEGER NOT NULL,
	"amount"	REAL NOT NULL,
	"datetime"	TEXT NOT NULL,
	FOREIGN KEY("sender_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY("receiver_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "MoneyStorages" (
	"id"	INTEGER NOT NULL,
	"denomination"	REAL NOT NULL,
	"amount"	INTEGER NOT NULL,
	"atm_id"	INTEGER NOT NULL,
	FOREIGN KEY("atm_id") REFERENCES "ATMs"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("denomination","atm_id")
);
CREATE TABLE IF NOT EXISTS "Banks" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Accounts" (
	"id"	INTEGER NOT NULL,
	"balance"	REAL NOT NULL,
	"credit_limit"	REAL NOT NULL,
	"bank_id"	INTEGER NOT NULL,
	FOREIGN KEY("bank_id") REFERENCES "Banks"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ATMs" (
	"id"	INTEGER NOT NULL,
	"bank_id"	INTEGER NOT NULL,
	FOREIGN KEY("bank_id") REFERENCES "Banks"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Withdrawals" (
	"id"	INTEGER NOT NULL,
	"account_id"	INTEGER NOT NULL,
	"amount"	REAL NOT NULL,
	"datetime"	TEXT NOT NULL,
	FOREIGN KEY("account_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CardTypes" (
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("name")
);
CREATE TABLE IF NOT EXISTS "Cards" (
	"card_number"	TEXT NOT NULL,
	"expiration_date"	TEXT NOT NULL,
	"pincode"	TEXT NOT NULL,
	"account_id"	INTEGER NOT NULL,
	"type"	TEXT,
	FOREIGN KEY("type") REFERENCES "CardTypes"("name") ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY("account_id") REFERENCES "Accounts"("id") ON DELETE NO ACTION ON UPDATE CASCADE,
	PRIMARY KEY("card_number")
);
COMMIT;
